apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: observability
  name: observability-read-only
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: observability
  name: observability-read-only
subjects:
  - kind: User
    name: marcelmonitoring
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: observability-read-only
  apiGroup: rbac.authorization.k8s.io
